"""add isPaid to renterTransaction

Revision ID: 237cdd13b8ef
Revises: 7bbf54307083
Create Date: 2022-12-06 10:43:33.125210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '237cdd13b8ef'
down_revision = '7bbf54307083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentertransaction', sa.Column('isPaid', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rentertransaction', 'isPaid')
    # ### end Alembic commands ###
