"""delete status from rentertransaction

Revision ID: 7bbf54307083
Revises: 
Create Date: 2022-11-29 18:51:21.132923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bbf54307083'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rentertransaction', 'active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentertransaction', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
